#!/usr/bin/python

# This script is needed, when SELinux is enabled:
# mailman_mail_t context cannot write to the directory
# @mmdir@/Mailman so when you change mm_cfg.py, 
# mailman cannot create the .pyc
#
# This script is called in the init script, which is run in unconfined_t
# so the .pyc is created and the AVC denial is avoided. (bz#481446)

import py_compile

py_compile.compile("@mmdir@/Mailman/mm_cfg.py")
